# Generated by Django 3.2.21 on 2023-10-10 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Podaj imię studenta', max_length=100)),
                ('last_name', models.CharField(help_text='Podaj nazwisko studenta', max_length=100)),
                ('kolokwium', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='kolokwium')),
                ('aktywnosc', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='aktywnosc')),
                ('egzamin_koncowy', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='egzamin koncowy')),
                ('avg', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
