# Generated by Django 3.2.21 on 2023-10-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_student_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mark',
            field=models.CharField(choices=[('mark_EUR', 'MARK_EUR'), ('mark_US', 'MARK_US')], default='mark_EUR', max_length=8),
        ),
    ]
